#ifndef __SYSTEM__H_
#define __SYSTEM__H_

#define MAX_DATA_LEN 32
#define MAC_ADDR_LEN 4
#define VER_LEN_LEN 1
#define TRAN_SEQ_LEN 1
#define CHECKSUM_LEN 1

#define LINK_LAY_HEAD_LEN (MAC_ADDR_LEN + VER_LEN_LEN + TRAN_SEQ_LEN + CHECKSUM_LEN)
#define LINK_LAY_MAX_LEN (MAX_DATA_LEN + LINK_LAY_HEAD_LEN)

#define MAC_LAY_HEAD_LEN 2
#define MAC_LAY_MAX_LEN     (LINK_LAY_MAX_LEN + MAC_LAY_HEAD_LEN)

#define LINK_LAY_OFFSET MAC_LAY_HEAD_LEN

#define MAC_TYPE_PLC  0
#define MAC_TYPE_2_4G 1

#endif /* __SYSTEM__H_ */
